package com.example.gb.model.enums;

public enum ExperimentEventType {
    CREATED,

    START_REQUEST, START_SUCCESS, START_FAIL,
    PAUSE_REQUEST, PAUSE_SUCCESS, PAUSE_FAIL,
    RESUME_REQUEST, RESUME_SUCCESS, RESUME_FAIL,
    FINISH_REQUEST, FINISH_SUCCESS, FINISH_FAIL,

    GB_UPSERT_REQUEST, GB_UPSERT_RESPONSE,
    GB_FETCH_REQUEST,  GB_FETCH_RESPONSE,

    ERROR
}
