server:
  port: 8080

spring:
  application:
    name: growthbook-ai-demo


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

growthbook:
  admin:
    base-url: http://growthbook:3100/api/v1
    token: ${GB_ADMIN_TOKEN:gb_admin_token_here}
  sdk:
    apiHost: ${GB_PUBLIC_API_HOST:http://localhost:3100}
    clientKey: ${GB_CLIENT_KEY_PUBLIC:gbpk_demo_key}
  owner: ${GB_OWNER:Vitaliy}
  project: ${GB_PROJECT:My First Project}


openai:
  api-key: ${OPENAI_API_KEY:sk-xxx}
  model: ${OPENAI_MODEL:gpt-4o-mini}
