package com.example.gb.service;

import com.example.gb.controller.DomInventoryController.Item;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

@Slf4j
@Service
@RequiredArgsConstructor
public class DomRegistryService {

    /**
     * Registry is a per-pageKey map:
     *   key:  pageKey = {siteId}__{pageId}
     *   val:  selector -> featureKey (generated by backend, canonical)
     *
     * NOTE: in-memory only for now (step 2 will move it to DB).
     */
    private final Map<String, Map<String, String>> registry = new ConcurrentHashMap<>();

    public Map<String, Map<String, String>> snapshot() {
        Map<String, Map<String, String>> out = new LinkedHashMap<>();
        registry.forEach((k, v) -> out.put(k, new LinkedHashMap<>(v)));
        log.info("🗺 DomRegistry snapshot pages: {}", out.keySet());
        return out;
    }

    /**
     * Main canonical API:
     * - Always returns backend-generated featureKey for (pageUrl, kind, selector)
     * - Never trusts bridge featureKey.
     * - Creates mapping if missing.
     */
    public String getOrCreateFeatureKey(String pageUrl, String kindRaw, String selectorRaw) {
        String pageUrlSafe = safe(pageUrl);
        String selector = safe(selectorRaw);
        String kindNormRaw = norm(kindRaw);

        if (pageUrlSafe.isEmpty() || selector.isEmpty() || kindNormRaw.isEmpty()) {
            log.warn("⚠ DomRegistry.getOrCreateFeatureKey called with empty args: url='{}' kind='{}' selector='{}'",
                    pageUrl, kindRaw, selectorRaw);
            // краще не зливати все в один ключ
            return "invalid__" + shortHash(pageUrlSafe + "|" + kindNormRaw + "|" + selector);
        }

        final String pageKey = toPageKeyFromUrl(pageUrlSafe);
        final Map<String, String> selectors =
                registry.computeIfAbsent(pageKey, k -> new ConcurrentHashMap<>());

        String resolvedKind = normalizeKind(kindNormRaw);
        if (resolvedKind == null) {
            log.warn("⚠ DomRegistry: unsupported kind='{}' selector='{}'", kindNormRaw, selector);
            resolvedKind = "x";
        }
        final String finalKind = resolvedKind;

        return selectors.computeIfAbsent(
                selector,
                sel -> generateFeatureKey(pageKey, finalKind, sel)
        );
    }


    /**
     * Sync inventory -> selector->featureKey map (warm-up).
     * IMPORTANT:
     * - Does NOT create/update GrowthBook features.
     * - Ignores featureKey coming from bridge.
     */
    public void syncAsync(String pageUrl, java.util.List<Item> items) {
        if (pageUrl == null || pageUrl.isBlank() || items == null || items.isEmpty()) {
            log.info("↷ DomRegistry: nothing to sync (url={}, items={})",
                    pageUrl, items == null ? 0 : items.size());
            return;
        }

        final String pageKey = toPageKeyFromUrl(pageUrl);
        final Map<String, String> selectors = registry.computeIfAbsent(pageKey, k -> new ConcurrentHashMap<>());

        log.info("🧠 DomRegistry: sync for {} ({} items)", pageKey, items.size());

        for (Item it : items) {
            String selector = safe(it.getSelector());
            String kindRaw  = norm(it.getKind());

            if (selector.isEmpty() || kindRaw.isEmpty()) continue;

            String kind = normalizeKind(kindRaw);
            if (kind == null) continue;

            selectors.computeIfAbsent(selector, sel -> generateFeatureKey(pageKey, kind, sel));
        }
    }

    public Optional<String> resolveFeatureKey(String pageUrl, String selector) {
        if (pageUrl == null || pageUrl.isBlank() || selector == null || selector.isBlank()) return Optional.empty();
        String pageKey = toPageKeyFromUrl(pageUrl);
        Map<String, String> map = registry.get(pageKey);
        if (map == null) return Optional.empty();
        return Optional.ofNullable(map.get(selector.trim()));
    }

    // ---------------------------------------------------------------------
    // pageKey = {siteId}__{pageId}
    // siteId  = host[_port]
    // pageId  = "/" -> "home", "/pricing" -> "pricing", "/docs/api" -> "docs_api"
    // ---------------------------------------------------------------------

    private static String toPageKeyFromUrl(String url) {
        try {
            URI u = URI.create(url);
            String siteId = toSiteId(u);
            String pageId = toPageId(u);
            return siteId + "__" + pageId;
        } catch (Exception e) {
            return "site__page";
        }
    }

    private static String toSiteId(URI u) {
        String host = Optional.ofNullable(u.getHost()).orElse("site");
        int port = u.getPort();
        String raw = (port > 0) ? host + "_" + port : host;
        return slug(raw, "site");
    }

    private static String toPageId(URI u) {
        String p = Optional.ofNullable(u.getPath()).orElse("/");
        if (p.isBlank() || "/".equals(p)) return "home";

        String raw = p.replaceAll("^/+", "")
                .replaceAll("/+$", "")
                .replace("/", "_");

        return slug(raw, "page");
    }

    // ---------------------------------------------------------------------
    // Kind normalization
    // ---------------------------------------------------------------------

    private static String normalizeKind(String kindRaw) {
        return switch (kindRaw) {
            case "heading", "h1", "h2", "h3", "h4", "h5", "h6", "role=heading" -> "h";
            case "cta", "button", "btn", "link", "a" -> "cta";
            default -> null;
        };
    }

    // ---------------------------------------------------------------------
    // Canonical key generation
    // featureKey = {pageKey}__{kind}__{slug(selectorTail)}_{hash(selector)}
    // ---------------------------------------------------------------------

    private static String generateFeatureKey(String pageKey, String kind, String selector) {
        String tail = selectorTail(selector);
        String slug = slug(tail, "el");
        String hash = shortHash(selector);

        String raw = pageKey + "__" + kind + "__" + slug + "_" + hash;

        String id = raw.toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9_\\-]", "_"); // лишаємо тільки дозволені

        return id.length() > 160 ? id.substring(0, 160) : id;
    }


    private static String selectorTail(String selector) {
        if (selector == null || selector.isBlank()) return "el";
        String s = selector.trim();
        int idx = s.lastIndexOf(">");
        if (idx >= 0 && idx + 1 < s.length()) {
            return s.substring(idx + 1).trim();
        }
        return s;
    }

    private static String slug(String s, String fallback) {
        if (s == null || s.isBlank()) return fallback;
        String out = s.trim().toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9]+", "_")
                .replaceAll("^_+|_+$", "")
                .replaceAll("_+", "_");
        if (out.isBlank()) return fallback;
        return out.length() > 80 ? out.substring(out.length() - 80) : out;
    }

    private static String norm(String s) {
        return s == null ? "" : s.trim().toLowerCase(Locale.ROOT);
    }

    private static String safe(String s) {
        return s == null ? "" : s.trim();
    }

    private static String shortHash(String s) {
        if (s == null) return "00000000";
        byte[] bytes = s.getBytes(StandardCharsets.UTF_8);
        int h = 1125899907;
        for (byte b : bytes) {
            h = 31 * h + (b & 0xff);
        }
        String hex = Integer.toHexString(h);
        if (hex.length() > 8) hex = hex.substring(hex.length() - 8);
        return ("00000000" + hex).substring(hex.length());
    }
}
